version: '3'

services:
  master:
    image: jenkins
    ports:
      - 80:8080
      - 50000:50000
    #command: /var/jenkins_home/update_jenkins.sh
    volumes:
      - /home/oracle/docker/jenkins/jenkins_home:/var/jenkins_home
